import Header from './Components/Header';
import { Nav } from './Components/Nav';
import { News } from './Components/News';
import { Question } from './Components/Question';
import { Schedule } from './Components/Schedule';
import { Services } from './Components/Services';
import { Video } from './Components/Video';
import { Objects } from './Components/Data';
import './globals.css'
import { Poppins } from 'next/font/google'
import Testimonial from './Components/Testimonial';
import Footer from './Components/Footer';

const pop = Poppins({
  subsets: ['latin'],
weight: ['500']})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={pop.className}>
        <Nav />
        {children}
       <Footer />
       </body>
    </html>
  )
}
