import Header from './Components/Header';
import Navbar from './Components/Navbar';
import News from './Components/News';
import Question from './Components/Question';
import Schedule from './Components/Schedule';
import Services from './Components/Services';
import Video from './Components/Video';
import Objects from './Components/Data';
import './globals.css'
import { Inter } from 'next/font/google'
import Testimonial from './Components/Testimonial';
import List from './Components/Footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

      

        <Navbar />
      
        {children}
        
       <List />
       </body>
    </html>
  )
}
